getTranslationDomain() $translation variable name typo fixed
Ex3v/FormErrorsBundle pull request #14
Opened 2017-08-09 23:02 UTC by spectrals

Fixes the "Call to a member function getConfig() on null" error

2017-08-10 05:52 UTC, Ex3v requested changes

2017-08-10 05:52 UTC, Ex3v commented on Services/FormErrorsParser.php
> +            }
Could you explain why are you rewriting `$errors` table inside of this loop?

2017-08-10 05:53 UTC, Ex3v commented
In general - thanks a lot! Let's just clear this one small thing out and it will be merged

2017-08-11 02:12 UTC, spectrals commented
Maciej, thanks for putting this bundle together. With some minor changes I found it pretty useful when building errors list for the API I'm working on.

I did few more commits recently - you may want to review them:
- Fixed deprecated twig extension declaration (Twig 2.0+ compatibility)
- Added handling for the case when form parent is null (it can be according to the phpdoc annotations)
- Translator is now moved to the parser service instead of a twig extension, label translation is now handled properly
- Netbeans project folders were removed (let me sure if there was a reason for them to be there :) )

2017-08-11 06:49 UTC, Ex3v commented
Oh man, that's what makes me happy - when someone says that I made job easier by this little helpful thing. Thanks!
The NetBeans thing has a simple explanation - that was my first bundle ever and I wasn't sure what I was doing ;) Thanks a lot for removing those. 
One thing I still miss as for today is lack of unit tests. I'm gonna write them one day.
I will try to take a look at all of your changes when I get myself to the office. Thanks once more!

2017-08-11 11:37 UTC, Ex3v approved these changes

2017-08-11 11:38 UTC, Ex3v commented
@spectrals could you please resolve conficts with `Twig/FormErrorsExtension.php`? Everything else looks great

2017-08-11 12:09 UTC, spectrals commented
Done! Thanks for reviewing these so quickly

2017-08-11 12:20 UTC, merged